parameters:
    db_url: '%env(DATABASE_URL)%'
    db_url_default: '%env(resolve:DATABASE_URL_DEFAULT)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    client.http.steam:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Steam\SteamClient
        arguments:
            - "%env(STEAM_API_KEY)%"

    client.communication.telegram:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Communication\TelegramClient
        arguments:
            - '%env(TELEGRAM_TOKEN)%'
            - '%env(TELEGRAM_GROUP_CHAT_ID)%'
            - '%env(TELEGRAM_ADMIN_CHAT_ID)%'

    repository.dbal.connection:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - url: '%db_url%'
              driver: 'pdo_pgsql'

    repository.dbal.connection_default:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - url: '%db_url_default%'
              driver: 'pdo_pgsql'

    repository.dbal:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\DbalRepository
        arguments:
            - '@repository.dbal.connection'

    repository.app.dbal:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\App\AppDbalRepository
        parent: repository.dbal
        autowire: false
        autoconfigure: false

    command.check:
        class: AdnanMula\Steam\NewGameNotifier\Entrypoint\Command\CheckNewGamesCommand
        arguments:
            - '@client.http.steam'
            - '@client.communication.telegram'
            - '@repository.app.dbal'
            - '%env(STEAM_ID_64)%'
        tags:
            - { name: console.command, command: 'new-game-notifier:check' }

    command.init:
        class: AdnanMula\Steam\NewGameNotifier\Entrypoint\Command\Environment\EnvironmentInitCommand
        arguments:
            - '@repository.dbal.connection_default'
            - '@repository.dbal.connection'
        tags:
            - { name: console.command, command: 'environment:init' }
