parameters:
    db_url: '%env(DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    client.http.steam:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Steam\SteamClient
        arguments:
            - "%env(STEAM_API_KEY)%"

    client.communication.telegram:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Communication\TelegramClient
        arguments:
            - '%env(TELEGRAM_TOKEN)%'
            - '%env(TELEGRAM_GROUP_CHAT_ID)%'
            - '%env(TELEGRAM_ADMIN_CHAT_ID)%'

    connection.dbal:
        class: Doctrine\DBAL\Connection
        factory: 'Doctrine\DBAL\DriverManager::getConnection'
        arguments:
            - url: '%db_url%'
              driver: 'pdo_pgsql'

    migration.dbal:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\DbalMigration
        arguments:
            - '@connection.dbal'

    repository.dbal:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\DbalRepository
        arguments:
            - '@connection.dbal'

    repository.app.dbal:
        class: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\App\AppDbalRepository
        parent: repository.dbal
        autowire: false
        autoconfigure: false

    command.check:
        class: AdnanMula\Steam\NewGameNotifier\Entrypoint\Command\CheckNewGamesCommand
        arguments:
            - '@client.http.steam'
            - '@client.communication.telegram'
            - '@repository.app.dbal'
            - '%env(STEAM_ID_64)%'
        tags:
            - { name: console.command, command: 'new-game-notifier:check' }

    command.init:
        class: AdnanMula\Steam\NewGameNotifier\Entrypoint\Command\InitDbCommand
        arguments:
            - '@migration.dbal'
        tags:
            - { name: console.command, command: 'new-game-notifier:init' }