parameters:
    db_url: '%env(resolve:DATABASE_URL)%'
    db_url_default: '%env(resolve:DATABASE_URL_DEFAULT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $steamUserId: '%env(STEAM_ID_64)%'
            string $apiKey: '%env(STEAM_API_KEY)%'
            string $telegramToken: '%env(TELEGRAM_TOKEN)%'
            string $groupChatId: '%env(TELEGRAM_GROUP_CHAT_ID)%'
            string $adminChatId: '%env(TELEGRAM_ADMIN_CHAT_ID)%'
            string $hltbToken: '%env(HLTB_TOKEN)%'
            Doctrine\DBAL\Connection $connection: '@repository.dbal.connection'
            Doctrine\DBAL\Connection $defaultConnection: '@repository.dbal.connection_default'

    repository.dbal.connection:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - url: '%db_url%'
              driver: 'pdo_pgsql'

    repository.dbal.connection_default:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - url: '%db_url_default%'
              driver: 'pdo_pgsql'

    AdnanMula\Steam\NewGameNotifier\Domain\:
        resource: '../src/Domain'

    AdnanMula\Steam\NewGameNotifier\Infrastructure\:
        resource: '../src/Infrastructure'

    AdnanMula\Steam\NewGameNotifier\Entrypoint\Command\:
        resource: '../src/Entrypoint/Command'
        tags: [ 'console.command' ]

    AdnanMula\Steam\NewGameNotifier\Domain\Model\App\AppRepository:
        alias: AdnanMula\Steam\NewGameNotifier\Infrastructure\Persistence\Repository\App\AppDbalRepository
